version: '3.1'
services:
  app:
    build:
#      context is stating the initial path. which is the root
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "50000:50000"
    # the SPRING_DATASOURCE_URL must connect to docker port
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/my_cms
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped

  PostgreSQL:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_cms
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5