spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5435/my_cms'
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      password: zacktest
  sql:
    init:
      platform: postgres
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      name: inhouse-transfers

# server properties
server:
  error:
    include-message: always
  port: 50000

# app properties
my-cms:
  app:
    jwtSecret: mycmsSecretKey
    jwtExpirationMs: '300000'
    jwtRefreshExpirationMs: '600000'
    # For testing
#    jwtExpirationMs: '60000'
#    jwtRefreshExpirationMs: '120000'