-- DDL
CREATE DATABASE my_cms;
GRANT ALL PRIVILEGES ON DATABASE "my_cms" TO zacktest;


-- DML
INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');

ALTER TABLE refreshtoken ALTER COLUMN id RESTART WITH 1;
ALTER SEQUENCE hibernate_sequence RESTART WITH 1;